# Generated by Django 3.2 on 2022-06-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=90)),
                ('correct', models.BooleanField()),
                ('start_idx', models.IntegerField(null=True)),
                ('end_idx', models.IntegerField(null=True)),
                ('evidence', models.CharField(blank=True, default='', max_length=2000)),
                ('is_published', models.BooleanField(null=True)),
                ('null_odds', models.FloatField(null=True)),
                ('_property', models.CharField(blank=True, default='', max_length=90)),
                ('question', models.CharField(blank=True, default='', max_length=1000)),
                ('score', models.FloatField(null=True)),
                ('text', models.CharField(blank=True, default='', max_length=1000)),
                ('wikidata_link', models.CharField(blank=True, default='', max_length=1000)),
                ('wikipedia_link', models.CharField(blank=True, default='', max_length=1000)),
                ('feeback_id', models.IntegerField(null=True)),
            ],
        ),
    ]
