# Generated by Django 3.2 on 2022-07-22 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, default='', max_length=100)),
                ('namespace', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('namespace_item_id', models.CharField(blank=True, default='', max_length=100)),
                ('candidate_created_at', models.DateTimeField(auto_now_add=True)),
                ('wikidata_entity', models.URLField(blank=True, default='')),
                ('wikidata_property', models.CharField(blank=True, default='', max_length=100)),
                ('data_value', models.JSONField(default=list)),
                ('data_type', models.CharField(blank=True, default='', max_length=100)),
                ('qualifiers', models.JSONField(default=dict)),
                ('references', models.JSONField(default=list)),
                ('shown_to_editors', models.IntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(auto_now=True)),
                ('evidence_highlight', models.JSONField(default=dict)),
                ('editor_feedback', models.BooleanField(default=False)),
                ('validated_by', models.CharField(blank=True, default='', max_length=100)),
                ('question', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
