# Generated by Django 3.2 on 2022-09-09 08:18

import backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='evidence_highlight',
            field=models.JSONField(blank=True, default=backend.utils.default_evidence_highlight, null=True),
        ),
    ]
