# Generated by Django 3.2 on 2022-08-05 11:35

import backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='data_value',
            field=models.JSONField(default=backend.utils.default_data_value),
        ),
        migrations.AlterField(
            model_name='fact',
            name='evidence_highlight',
            field=models.JSONField(default=backend.utils.default_evidence_highlight),
        ),
        migrations.AlterField(
            model_name='fact',
            name='feedback',
            field=models.JSONField(default=backend.utils.default_feedback),
        ),
        migrations.AlterField(
            model_name='fact',
            name='meta_information',
            field=models.JSONField(default=backend.utils.default_meta_information),
        ),
        migrations.AlterField(
            model_name='fact',
            name='references',
            field=models.JSONField(default=backend.utils.default_references),
        ),
    ]
