# Generated by Django 3.2 on 2022-09-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_fact_evidence_highlight'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fact',
            unique_together={('entity', 'property_data', 'value_data')},
        ),
    ]
